import os

GPU_THRESHOLDS = {
    "H100_PRICE_HIGH": 2.0,
    "A100_PRICE_HIGH": 1.0,
    "H100_AVAILABILITY_LOW": 1200,
    "A100_AVAILABILITY_LOW": 3000
}

MARKET_THRESHOLDS = {
    "NVDA_HIGH": 200,
    "BTC_HIGH": 60000,
    "ETH_HIGH": 1800,
    "AKT_HIGH": 0.75
}

API_KEYS = {
    "RUNPOD": os.getenv("RUNPOD_API_KEY"),
    "VAST": os.getenv("VAST_API_KEY"),
    "LAMBDA": os.getenv("LAMBDA_API_KEY")
}

DASHBOARD_TITLE = "AI-RPCT Dashboard"
