#!/bin/bash
cd ~/AI-RPCT
source venv/bin/activate
export PYTHONPATH="$(pwd):${PYTHONPATH}"
export MPLCONFIGDIR="$(pwd)/.matplotlib"
mkdir -p "$MPLCONFIGDIR"

echo "=============================="
echo "AI-RPCT DAILY RUN"
echo "$(date)"
echo "=============================="

python collectors/collect_market_data.py
python collectors/collect_gpu_data.py
python engine/calculate_rpct.py

python analytics/provider_rankings.py
python analytics/provider_health.py
python analytics/provider_marketshare.py
python analytics/provider_concentration.py
python analytics/provider_credentials.py
python analytics/provider_readiness.py
python analytics/shortage_probability.py
python analytics/gpu_scarcity_index.py
python analytics/forecast_signal.py
python analytics/trend_engine.py
python analytics/time_series_forecast.py
python analytics/market_regime.py
python analytics/predictor.py
python analytics/investor_metrics.py
python analytics/investor_dashboard.py
python analytics/executive_dashboard.py
python analytics/backtest.py
python analytics/forecast_accuracy.py
python analytics/provider_history.py
python analytics/alert_engine.py
python analytics/data_quality.py
python analytics/production_readiness.py
python analytics/operational_status.py
python analytics/data_validator.py

python api/metrics.py
python database/init_db.py
python database/import_csv.py
python analytics/daily_report.py
python analytics/research_snapshot.py
python dashboard/dashboard.py

echo "DONE"
python analytics/ai_infrastructure_index.py
python analytics/index_history.py
python analytics/archive_daily_snapshot.py
python analytics/provider_daily_metrics.py
python analytics/provider_dominance_index.py
python analytics/cron_health.py
python analytics/data_moat_score.py
python analytics/daily_intelligence_summary.py
python analytics/archive_raw_provider_data.py
python analytics/data_freshness.py
python analytics/live_provider_status.py
python analytics/provider_data_mode.py
python analytics/public_beta_status.py
python analytics/commercial_readiness.py
python analytics/launch_readiness.py
python analytics/provider_preflight.py
python analytics/live_provider_ingest.py
python analytics/provider_preflight.py
python analytics/archive_live_provider_data.py
python analytics/live_gpu_price_index.py
python analytics/live_gpu_price_history.py
python analytics/live_offer_summary.py
python analytics/live_gpu_rankings.py
python analytics/gpu_market_movers.py
python analytics/live_gpu_alerts.py
python analytics/weekly_infrastructure_report.py
python analytics/provider_comparison.py
python analytics/provider_health.py
python analytics/provider_reliability_ranking.py
python analytics/provider_reliability_gaps.py
python analytics/gpu_price_trend_signal.py
python analytics/core_signal_history.py
python analytics/core_history_audit.py
python analytics/core_provenance_audit.py
python analytics/core_signal_quality.py
python analytics/core_intelligence_readiness.py
python analytics/paid_beta_gate.py
python analytics/terminal_summary.py
python analytics/api_inventory_runtime.py
python analytics/market_data_moat_status.py
python analytics/gpu_watchlist_intelligence.py
python analytics/frontier_gpu_index.py
python analytics/intelligence_signal_score.py
python analytics/daily_terminal_brief.py
python analytics/gpu_category_index.py
python analytics/provider_coverage_score.py
python analytics/manual_snapshot_ingest.py
python analytics/manual_snapshot_quality.py
python analytics/coverage_universe_status.py
python analytics/scarcity_watchlist.py
python analytics/terminal_risk_score.py
python analytics/executive_ai_infrastructure_memo.py
python analytics/research_preview_brief.py
python analytics/live_data_quality_score.py
python analytics/terminal_trend_history.py
python analytics/market_pulse_snapshot.py
python analytics/provider_market_share_history.py
python analytics/market_intelligence_snapshot.py
python analytics/gpu_price_volatility.py
python analytics/live_provider_dominance.py
python analytics/ai_infrastructure_pulse.py
python analytics/investor_snapshot.py
python analytics/customer_value_score.py
python analytics/founder_dashboard_summary.py
python analytics/sales_readiness.py
python analytics/history_summary.py
python analytics/feedback_summary.py
python analytics/public_usage_snapshot.py
python analytics/customer_pipeline_summary.py
python analytics/product_readiness_score.py
python analytics/founder_operating_dashboard.py
python analytics/api_product_status.py
python analytics/product_terminal_readiness.py
python analytics/monetization_readiness.py
