from pathlib import Path
from datetime import datetime, timezone

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

SOURCE = Path("data/reports/customer_report_pdf_ready_v1.md")
TARGET = Path("data/reports/customer_report_v1.pdf")


def customer_report_pdf_export_v1():
    if not SOURCE.exists():
        return {
            "status": "missing_source",
            "source": str(SOURCE)
        }

    text = SOURCE.read_text()

    TARGET.parent.mkdir(parents=True, exist_ok=True)

    c = canvas.Canvas(str(TARGET), pagesize=letter)
    width, height = letter

    # PDF metadata / branding
    try:
        c.setTitle("AI-RPCT Customer Intelligence Report")
    except Exception:
        pass
    try:
        c.setAuthor("AI-RPCT")
    except Exception:
        pass
    try:
        c.setSubject("GPU Cloud Market Intelligence")
    except Exception:
        pass
    # Keywords may not be available via public API in all ReportLab versions
    try:
        c.setKeywords("GPU, Cloud, Pricing, Capacity, Intelligence")
    except Exception:
        try:
            c._doc.info.keywords = "GPU, Cloud, Pricing, Capacity, Intelligence"
        except Exception:
            pass

    def _draw_header_footer(canv, page_w, page_h):
        canv.saveState()
        canv.setFont("Helvetica-Bold", 12)
        canv.drawString(inch, page_h - 0.75 * inch, "AI-RPCT")
        canv.setFont("Helvetica", 10)
        canv.drawString(inch, page_h - 0.95 * inch, "GPU Cloud Market Intelligence")

        canv.setFont("Helvetica-Oblique", 8)
        canv.drawString(inch, 0.75 * inch, "Generated by AI-RPCT")
        canv.drawRightString(page_w - inch, 0.75 * inch, "Customer Intelligence Export")
        canv.restoreState()

    x = inch
    # start below header
    y = height - 1.25 * inch
    line_height = 14

    c.setFont("Helvetica", 10)

    # draw header on first page
    _draw_header_footer(c, width, height)

    for raw_line in text.splitlines():
        line = raw_line[:95]

        if y < inch:
            c.showPage()
            # draw header/footer on new page
            _draw_header_footer(c, width, height)
            c.setFont("Helvetica", 10)
            y = height - 1.25 * inch

        c.drawString(x, y, line)
        y -= line_height

    c.save()

    return {
        "status": "saved",
        "file": str(TARGET),
        "generated_at": datetime.now(timezone.utc).isoformat()
    }
